install.packages("devtools", repos = "https://cloud.r-project.org")
install.packages("coxme", repos = "https://cloud.r-project.org")
install.packages("fastDummies", repos = "https://cloud.r-project.org")
devtools::install_github("https://github.com/wfmueller29/helphlme.git")
devtools::install_github("https://github.com/wfmueller29/callframe.git")
devtools::install_github("https://github.com/wfmueller29/SLAM.git")
devtools::install_github("https://github.com/wfmueller29/consoler.git")
install.packages("lmerTest", repos = "https://cloud.r-project.org")
install.packages("tidyverse", repos = "https://cloud.r-project.org")
install.packages("rsample", repos = "https://cloud.r-project.org")
install.packages("future", repos = "https://cloud.r-project.org")
install.packages("kableExtra", repos = "https://cloud.r-project.org")
install.packages("survival", repos = "https://cloud.r-project.org")
install.packages("survminer", repos = "https://cloud.r-project.org")
install.packages("ggplotify", repos = "https://cloud.r-project.org")
install.packages("sjPlot", repos = "https://cloud.r-project.org")
install.packages("lme4", repos = "https://cloud.r-project.org")
install.packages("cowplot", repos = "https://cloud.r-project.org")
install.packages("RColorBrewer", repos = "https://cloud.r-project.org")
install.packages("viridis", repos = "https://cloud.r-project.org")
# install.packages("MLmetrics", repos = "https://cloud.r-project.org")
install.packages("yardstick", repos = "https://cloud.r-project.org")
install.packages("beepr", repos = "https://cloud.r-project.org")
install.packages("tinytex", repos = "https://cloud.r-project.org")
install.packages("flextable", repos = "https://cloud.r-project.org")
tinytex::install_tinytex()
# install.packages("rms", repos = "https://cloud.r-project.org")
# install.packages("base.rms", repos = "https://cloud.r-project.org")
install.packages("nnet", repos = "https://cloud.r-project.org")
install.packages("pheatmap", repos = "https://cloud.r-project.org")
