---
title: "SLAM Metabolic Class COD and healthcard"
author: "William Mueller"
data: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:
    df_print: paged
--- 

```{r setup, warning=FALSE, message=FALSE, echo=FALSE}
library(consoler)
library(SLAM)
set.seed(365)

# setting global knitr options for r markdown output
knitr::opts_chunk$set(autodep = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = FALSE)
```

# Load in input data

```{r read in censuses}
census_04_path <- "/Users/williammueller/programs/metabolic_class/analysis/04_create_census/output/20250426_all_cohort/complete_census.csv"
census_06_path <- "/Users/williammueller/programs/metabolic_class/analysis/06_create_figures/output/20250426_all_cohort/complete_census.csv"
healthcard_path <- "/Users/williammueller/programs/metabolic_class/analysis/98_healthcard_cod/data/SLAM Healthcard.xlsx"

census_04 <- read.csv(census_04_path)
census_06 <- read.csv(census_06_path)
healthcard <- readxl::read_xlsx(healthcard_path)
```

## Clean Healthcard

```{r clean healthcard}
new_names <- c(
  tag = "tag", dod = "Date of Death",
  created_data = "Created Date",
  recovery_data = "Recovery Date", condition = "Condition"
)

healthcard <- consoler::rename(healthcard, new_names)

unique(healthcard$condition)

clean_conditions <- list()
clean_conditions$fighting <- c("Fighting", "fighting")
clean_conditions$dermatitis <- c("Dermatitis", "Skin Reaction", "Red Skin")
clean_conditions$alopecia <- c("Alopecia/Barbering")
clean_conditions$trauma <- c("traumatic injury", "Tramatic Injury", "Traumatic Injury")
clean_conditions$dehydration <- c("Dehydrated", "Dehydration")
clean_conditions$seizure <- c("Seizure")
clean_conditions$edema <- c("Swelling", "Swollen Feet", "edema", "Edema", "Swollen Hindfoot")
clean_conditions$flood <- c("Flooded Cage", "cage flood", "Cage Flood")
clean_conditions$mass <- c("Mass", "mass", "Mass (size in mm)", "Mass ")
clean_conditions$prolapse <- c("Prolapse", "prolapse", "Prolapse (rectal/genital)", "Prolapsed Penis", "Rectal Prolapse", "Prolapse ", "Penile Prolapse", "prolpase")
clean_conditions$lesion <- c("Lesion", "lesion", "Lesions")
clean_conditions$weight_loss <- c("Weight Loss", "weight loss", "Losing Weight")
clean_conditions$bleed <- c("Bleeding", "Rectal Bleeding", "Nose Bleeding", "bleeding", "Vaginal Bleeding")
clean_conditions$irritation <- c("Irritation")
clean_conditions$lethargy <- c("Lethargy", "lethargy", "Lethargic", "Slow Moving")
clean_conditions$hunch <- c("Hunched Posture", "Thin/Hunched")
clean_conditions$dyspnea <- c("Dyspnea", "dyspnea", "Dyspnea ", "Increased RR", "Dyspnea (Labored Breathing)")
clean_conditions$distented_abdomen <- c("Distended Abdomen")
clean_conditions$abscess <- c("Abscess")
clean_conditions$paralysis <- c("Paralysis")
clean_conditions$eye_problem <- c("Eye Problem", "eye problem", "Eye Issue")
clean_conditions$ear_problem <- c("Ear Problem", "Ear Problems")
clean_conditions$head_tilt <- c("Head Tilt", "head tilt")
clean_conditions$discharge <- c("Discharge", "Vaginal Discharge")
clean_conditions$moribund <- c("Moribund", "moribund", "Moribund ", "Moribund (near death)")
clean_conditions$urinary <- c("Urinary Distress", "Urine Staining", "Excessive Urination", "Unable to Urinate")
clean_conditions$gait <- c("Abnormal Gait", "Unsteady Gait", "Hindlimb Weakness", "Favoring Hindlimb")
clean_conditions$malocclusion <- c("Malocclusion")
clean_conditions$hernia <- c("Hernia")
clean_conditions$swollen_testicle <- c("Swollen Testicle", "Enlarged testicle")
clean_conditions$thin <- c("Thin")
clean_conditions$skin_tag <- c("Skin Tag")
clean_conditions$low_glucose <- c("Low Glucose")
clean_conditions$discolored_urine <- c("Discolored Urine", "Cloudy/Tinted Urine")
clean_conditions$cyanotic <- c("Cyanotic")
clean_conditions$organomegaly <- c("Enlarged Organs")
clean_conditions$permanent_defect <- c("Permanent Defect")
clean_conditions$hydrocehpalus <- c("Hydrocephalus")
clean_conditions$diarrhea <- c("Diarrhea")
clean_conditions$nutritional_support <- c("Nutritional Support")
clean_conditions$low_temp <- c("Low Temperature", "Low body temperature")
clean_conditions$na <- c(NA)
clean_conditions$blood_in_cage <- c("Blood in Cage")
clean_conditions$red_paws <- c("Red Paws")
clean_conditions$paralysis <- c("paralysis")
clean_conditions$behavior <- c("odd behavior")
clean_conditions$other <- c("Other")
clean_conditions$enlarged_bladder <- c("enlarged bladder")
clean_conditions$tail_issue <- c("Tail Issue")


healthcard
```

