---
title: "SLAM Glucose Trajectory Analysis"
author: "William Mueller"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:
    df_print: paged
params:
  model_dir: "20220602_013532_all"
---


```{r packages, warning=FALSE, message=FALSE, echo=TRUE}

library(ggplot2)
library(kableExtra)
library(gridExtra)
library(tidyverse)
library(survival)
library(lcmm)
library(future)
library(helphlme)


#setting global knitr options for r markdown output
knitr::opts_chunk$set(autodep = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = FALSE)
knitr::opts_chunk$set(include = FALSE)
knitr::opts_chunk$set(results = "asis")

```

## Render
```{r render, eval = FALSE}
model_dir <- "20220510_124214_test"
output_dir <- normalizePath(file.path("output", model_dir))
rmarkdown::render(input = "04_model_select.Rmd",
                  output_dir = output_dir,
                  params = list(model_dir = model_dir))

model_dir <- "20220523_121216_test"
output_dir <- normalizePath(file.path("output", model_dir))
rmarkdown::render(input = "04_model_select.Rmd",
                  output_dir = output_dir,
                  params = list(model_dir = model_dir))

```

```{r load models}
path <- normalizePath(file.path("..", "03_model", "output", params$model_dir))
cf_path <- normalizePath(file.path(path, "cf.RDATA"))
models_path <- normalizePath(file.path(path, "models.RDATA"))
df_list_path <- normalizePath(file.path(path, "df_list.RDATA"))

load(file = cf_path)
load(file= models_path)
load(file = df_list_path)

```

```{r group models into lists}
cf$final_model <- models

cf <- as.data.frame(cf)

cf_nest <- cf %>% nest_by(`data|oc`, `$age_var`)
```


```{r step1 mo_eval output, include = TRUE, eval = params$eval_step1, fig.height=7, fig.width=12}
for(i in seq_len(nrow(cf_nest))) {
  models <- cf_nest$data[[i]]$final_model
  mo_eval <- helphlme::compare_models(models)
  print(kable(mo_eval$table, caption = names(models)) %>% 
        kable_styling("striped", full_width = F))
  print(mo_eval$plot + labs(title = names(models)))
}
```

```{r model eval, include = TRUE, results = 'asis'}
for(i in seq_len(nrow(cf_nest))) {
  cf <- cf_nest$data[[i]]
  outcome <- cf$oc[[1]]
  df <- df_list[[cf$data[[1]]]]
  ylim <- c(min(df[[outcome]]), max(df[[outcome]]))
  data_oc <- cf_nest$`data|oc`[[i]]
  age_var <- cf_nest$`$age_var`[[i]]
  header <- paste("Data|Outcome =",
                  data_oc, 
                  "; Age Variable =", 
                  age_var, 
                  sep = " ")
  cat("\n\n## ", header, "\n\n")
  pred <-  helphlme::create_pred_df(df = df,
           age_vars = paste(age_var, c("", "2"), sep = ""),
           fixcov = c("sex" = 0, "strain" = 0))
  helphlme::display_classes(df = pred,
                                 cf$final_model,
                                 age_var,
                                 main = header,
                                 xlab = age_var,
                                 ylab = outcome,
                            ylim = ylim)
  mo_eval <- helphlme::compare_models(cf$final_model)
  print(kable(mo_eval$table) %>%  kable_styling("striped", full_width = F))
  print(mo_eval$plot)
}


```

```{r select model in nest}
final_models <- data.frame()
for(i in seq_len(nrow(cf_nest))) {
  age_var <- cf_nest$`$age_var`[[i]]
  data_oc <- cf_nest$`data|oc`[[i]]
  cf <- cf_nest$data[[i]]
  models <- cf$final_model
  mo_eval_table <- helphlme::compare_models(models)$table
  cf <- cbind(cf, mo_eval_table) %>%
    mutate(smallest_greater_5 = ifelse(`Smallest Class (%)` >= 5, 1, 0)) %>%
    arrange(-smallest_greater_5, eval(as.symbol("BIC")))
  final_model_df_row <- as.data.frame(cf)[1, ]
  final_model_df_row$age_var <- age_var
  final_model_df_row$data_oc <- data_oc
  final_model_df_row$model_name <- paste(data_oc, age_var, sep = "_")
  final_models <- rbind(final_models, final_model_df_row)
}

```

```{r save final models}
output_path <- normalizePath(file.path("output", params$model_dir))

R.utils::copyDirectory(from = path, output_path)

final_model_path <- file.path(output_path, "final_models.RDATA")

save(final_models, file = final_model_path)

```

