---
title: "SLAM Metabolic Class Figures"
author: "William Mueller"
data: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:
    df_print: paged
params:
  model_dir: "20220602_013532_all"
---

```{r setup, warning=FALSE, message=FALSE, echo=FALSE}
library(helphlme)
library(tidyverse)
library(kableExtra)
library(survival)
library(survminer)
library(ggplotify)
library(sjPlot)
library(lme4)
library(cowplot)
library(RColorBrewer)
# setting global knitr options for r markdown output
knitr::opts_chunk$set(autodep = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = FALSE)



mega_pal <- rep(palette(), 40)

```

## Analysis

### Load Models

```{r load models}
path <- normalizePath(file.path("..", "04_model_select", "output", params$model_dir))

load_output <- function(file_name) {
  file_path <- normalizePath(file.path(path, paste0(file_name, ".RDATA")))
  load(file = file_path, envir = .GlobalEnv)
}

load_output("cf")
load_output("df_list")
load_output("final_models")
load_output("models")
load_output("config")

# load in main_cat_surv
load(file = "../04b_healthcard_cod/output/main_cat_surv.RDATA")
# load in health
load(file = "../04b_healthcard_cod/output/health.RDATA")
# load in dvr
load(file = "../04b_healthcard_cod/output/dvr.RDATA")

# load in prediction data
load(file = "../04c_prediction_data/output/dfs_prediction.RDATA")

final_models$dfs <- lapply(final_models$data, function(name) {
  df_list[[name]]
})
```

#### Name Model Variables

```{r naming}

final_models <- final_models %>%
  mutate(oc_name = ifelse(oc == "bw", "Body Weight", 
                           ifelse(oc == "gluc", "Glucose",
                                  ifelse(oc == "fat", "Body Fat", 
                                         ifelse(oc == "lean", "Lean Mass", NA))))) %>%
  mutate(oc_units = ifelse(oc == "bw" | oc == "fat" | oc == "lean", "(g)", 
                           ifelse(oc == "gluc", "(mg/dL)", NA))) %>%
  mutate(age_var_name = ifelse(age_var == "age_wk", "Age", 
                               ifelse(age_var == "per_age_wk", "Relative Age", NA))) %>%
  mutate(age_var_units = ifelse(age_var == "age_wk", "(weeks)", 
                                ifelse(age_var == "per_age_wk", "(%)", NA)))

final_models_info <- final_models %>%
  select(-final_model)

```

#### Healthcard Cleaning
```{r healthcard}

# now we have to add the health card information. lets convert it to wide format
# so that we can add it to the subject summary 
# create wave for health
health <- health %>%
  group_by(tag) %>%
  arrange(date_created) %>%
  mutate(wave =row_number()) %>%
  ungroup()
health_wide <- pivot_wider(health,
                       id_cols = c("idno", "tag", "dod"),
                       names_from = "wave",
                       names_prefix = "condition_",
                       values_from = "condition_clean") 

health_wide_heat <- pivot_wider(health,
                                id_cols = c("idno", "tag", "dod"),
                                names_from = "condition_clean",
                                values_from = "condition_clean")

health_wide_heat <- health_wide_heat 

col_of_interest <- 4:length(health_wide_heat)

health_wide_heat[, col_of_interest] <- lapply(health_wide_heat[, col_of_interest],
                                   function(col) {
                                     ifelse(col == "NULL", 0, 1)
                                   }) 

count <- as.data.frame(apply(health_wide_heat[, col_of_interest], 2, sum))

count

names(count) <- "n"
count$condition <- rownames(count)
rownames(count) <- NULL

# select interesting healthcard 
count <- arrange(count, -n)

# save healthcard count
write.csv(count, file = "output/conditions_and_counts.csv")
```

### Class Analysis

#### Create Summary Dataframe
```{r create summary dataframe}
merge_dvr <- dvr %>%
  select(idno, cod, dod, cod_coded, cod_1:cod_4_parens)

merge_health <- health_wide_heat %>%
  select(-dod, -idno)

subject_sum <- main_cat_surv %>%
  select(idno,
         tag,
         sex,
         strain,
         dead_censor,
         fu_age_wk,
         le_wk,
         cod,
         lastdate,
         maxdate,
         tod) %>%
  mutate(idno = as.numeric(idno)) %>%
  left_join(merge_dvr, by = "idno")

# check na's after merging
apply(apply(subject_sum, 2, is.na), 2, sum)

# obs goe from 1304 to 1310, so their are duplicates, lets find these duplicates
# and choose the correct one
id <- subject_sum$idno
subject_sum[duplicated(id) | duplicated(id, fromLast = TRUE),]

# if there a duplicates, we are going to take the observation with the cod.y
# that is not NA or Undetermined. If there is no NA or undetermined, we are 
# going to take the observation with the later dod
subject_sum <- subject_sum %>%
  group_by(idno) %>%
  # cod_effective is 0 if "undetermined" or is.na
  mutate(cod_effective = ifelse(cod.y == "Undetermined" | is.na(cod.y), 0, 1)) %>%
  arrange(desc(cod_effective), desc(dod)) %>%
  distinct(idno, .keep_all = TRUE) %>%
  ungroup() %>%
  as.data.frame() %>%
  rename(cod_census = cod.x,
         cod_dvr = cod.y)

subject_sum <- subject_sum %>%
  left_join(merge_health, by = "tag")

```

#### Create Census Dataframe
```{r census data frame}
# will number classes so that all classes of list given to function
# are labelled uniquely
make_census <- function(cf_row) {
  model <- unlist(cf_row$final_model, recursive = FALSE)
  class_df <- model$pprob
  
  main <- df_list[[cf_row$data]]
  
  # add class_df to main
  census <- main %>%
    mutate(idno = as.numeric(idno)) %>%
    left_join(class_df, by = "idno") %>%
    distinct(idno, .keep_all = T) %>%
    select(class, idno, cohort, starts_with("prob")) %>%
    filter(!is.na(class)) %>%
    mutate(idno = as.character(idno)) 
  
  # add survival information to census
  census <- census %>%
    mutate(idno = as.numeric(idno)) %>%
    left_join(subject_sum, by = "idno") %>%
    mutate(
      age_wk_death = le_wk,
      dead_nat = dead_censor
    )
  
  # return census
  census
}


final_models$census <- lapply(seq_len(nrow(final_models)), function(i) {
  cf_row <- final_models[i,]
  make_census(cf_row)
})


```


#### Create Table 1
```{r create table 1}
source("R/t1.R")

final_models$t1_raw <- lapply(final_models$census, t1, columns = c("sex", "strain"))

```

#### Perform Chi-squared Test
```{r chi squared test}
source("R/chi_test.R")

chi_results <- lapply(final_models$census,
                               chi_test,
                               columns = c("sex", "strain"))

final_models$chi_df <- chi_results$dfs
final_models$chi_test <- chi_results$tests

```

#### Create clean t1
```{r clean t1}
source("R/clean_t1.R")

final_models$clean_t1 <- lapply(final_models$census, 
                   clean_t1,
                   columns = c("sex", "strain"))
```

### Surival Analysis 
```{r surv analysis}
source("R/surv.R")

attach(final_models)
final_models$kap_plot <- lapply(1:nrow(final_models), function(i) {
  kap_plot_all(census[[i]], 
               var = "class", 
               ptitle = paste(oc_name[[i]], 
                              age_var_name[[i]],
                              "KM", 
                              sep = " "))
})

```

### Trajectory Fixed Effects Plotted

```{r fixed effects, include = FALSE}
source("R/traj_plot.R")

if (is.null(config$sex) & is.null(config$strain)) {
  fixcov <- c(sex = 0, strain = 0)
} else if (is.null(config$sex)) {
  fixcov <- c(strain = 0)
} else if (is.null(config$strain)) {
  fixcov <- c(sex = 0)
} else {
  fixcov <- NULL
}

attach(final_models)
final_models$traj_pred <- lapply(1:nrow(final_models), function(i) {
  traj_plot(df = dfs[[i]],
            mo = final_model[[i]], 
            t1 = t1_raw[[i]],
            age_var = age_var[[i]], 
            y_var = oc[[i]], 
            title = paste("Predicted", 
                          oc_name[[i]], 
                          "Trajectories across",
                          age_var_name[[i]],
                          sep = " "),
            ylab = paste(oc_name[[i]], 
                         oc_units[[i]],
                         sep = " "),
            xlab =  paste(age_var_name[[i]], 
                         age_var_units[[i]],
                         sep = " "),
            fixcov = fixcov)
  # can render this plot with ggdraw or plot_grid
  plot <- recordPlot()
})

```

### Create Observed Trajectory Plots

```{r observed plots, include = FALSE}
attach(final_models)
final_models$traj_obs <- lapply(1:nrow(final_models), function(i){
  plot <- traj_obs(main = census[[i]],
                   df = dfs[[i]],
                   t1 = t1_raw[[i]], 
                   age_var = age_var[[i]],
                   y_var = oc[[i]],
                   title = paste("Observed",
                                 oc_name[[i]],
                                 "Trajectory with",
                                 age_var_name[[i]],
                                 sep = " "),
                   ylab = paste(oc_name[[i]],
                                oc_units[[i]],
                                sep = " "),
                   xlab = paste(age_var_name[[i]],
                                age_var_units[[i]],
                                sep = " "
                                ))
  
  plot
})


lapply(final_models$traj_obs, print)

  
```

### Create Spaghettie Plots

```{r spag plot}

plot_spag <- function(data, x, y, id, title = " ", xlab = " ", ylab = " ") {
  x <- paste0(x, "_ns")
  ggplot2::ggplot(
    data = data,
    mapping = ggplot2::aes_string(
      x = x,
      y = y,
      group = id
    )
  ) +
    #    ggplot2::geom_point() +
    ggplot2::geom_line() +
    ggplot2::geom_smooth(
      data = data,
      mapping = ggplot2::aes_string(
        x = x,
        y = y,
        group = NULL
      ) 
    ) +
    labs(title = title, 
         x = xlab,
         y = ylab)
}

attach(final_models)
lapply(1:nrow(final_models), function(i) {
  plot_spag(data = dfs[[i]],
            x = age_var[[i]],
            y = oc[[i]],
            id = subject[[i]],
            title = paste(oc_name[[i]],
                          age_var_name[[i]],
                          "Spaghetti Plot",
                          sep = " "),
            xlab = paste(age_var_name[[i]], age_var_units[[i]], sep = " "),
            ylab = paste(oc_name[[i]], oc_units[[i]], sep = " "))
})

```

```{r create prediction results}
for (subset_name in names(dfs_prediction)) {
  subset <- list()
  for (i in seq_len(nrow(final_models))) {
    data_name <- final_models$data[[i]]
    dfs_pred_list <- dfs_prediction[[subset_name]][[data_name]]
    subset[i] <- list(dfs_pred_list)
  }
  final_models[[subset_name]] <- subset
}

predict_model <- function(data,
                          model,
                           vars,
                           center,
                           scale,
                           ref_data = NULL) {
  pred_df <- helphlme::prep_hlme(df = data, 
                                 vars = vars,
                                 center = center,
                                 scale = scale, 
                                 ref_data = ref_data)
  model$call[[1]] <- "hlme"
  
  prediction <- lcmm::predictClass(model = model,
                     newdata = pred_df)
  
  prediction
}

predict_model_list <- function(data_list, 
                               model,
                               vars, 
                               center, 
                               scale, 
                               ref_data = NULL) {
  lapply(data_list,
         predict_model,
         model = model,
         vars = vars,
         center = center,
         scale = scale,
         ref_data = ref_data)
}

prediction_columns <- names(dfs_prediction)[-1]

predict_model_subset <- function(subset, vars, center, scale) {
  lapply(seq_len(nrow(final_models)), function(i){
    predict_model_list(data = final_models[[subset]][[i]],
                       model = final_models$final_model[[i]],
                       vars = vars,
                       center = center, 
                       scale = scale,
                       ref_data = final_models$dfs[[i]])
                       
  })
}

list <- lapply(prediction_columns, function(col) {
  predict_model_subset(subset = col,
                       vars = c("age_wk", "age_wk2"),
                       center = TRUE,
                       scale = FALSE)
})
```
