---
title: "SLAM Glucose Trajectory Analysis"
author: "William Mueller"
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:
    df_print: paged
params:
  input_path: "../02_model/output/itp_genotyped_treat_F.yaml"
---


```{r packages, warning=FALSE, message=FALSE, echo=TRUE}
library(ggplot2)
library(kableExtra)
library(gridExtra)
library(tidyverse)
library(survival)
library(lcmm)
library(future)
library(helphlme)


# setting global knitr options for r markdown output
knitr::opts_chunk$set(autodep = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = FALSE)
knitr::opts_chunk$set(include = FALSE)
knitr::opts_chunk$set(results = "asis")
```

```{r read input yaml}
# for the case when we are not running with RStudio
if (!exists("params")) {
  params <- list()
  params$input_path <- "../02_model/output/test_local.yaml"
}

input <- yaml::read_yaml(file = params$input_path)
```

```{r load models}
cf_path <- input$cf_path
models_path <- input$models_path
datasets_path <- input$datasets_path

load(file = cf_path)
load(file = models_path)
load(file = datasets_path)
config <- yaml::read_yaml(input$config_path)
```

```{r group models into lists}
cf$final_model <- models

cf <- as.data.frame(cf)

number_of_datasets <- length(unique(cf$dataset_index))
cf_nest <- list(dataset_index = unique(cf$dataset_index))

cf_nest$cf <- lapply(seq_len(number_of_datasets), function(i) {
  row_index <- cf$dataset_index == i
  cf[row_index, ]
})
```

```{r step1 mo_eval output, include = TRUE, fig.height=7, fig.width=12}
for (i in seq_len(number_of_datasets)) {
  data_id <- unique(cf_nest$cf[[i]]$data)
  cat("\n\n", data_id, "\n\n")
  models <- cf_nest$cf[[i]]$final_model
  mo_eval <- helphlme::compare_models(models)
  table <- kableExtra::kable(mo_eval$table, caption = names(models))
  table <- kableExtra::kable_styling(table, "striped", full_width = FALSE)
  print(table)
  print(mo_eval$plot + labs(title = names(models)))
}
```

```{r model eval, include = TRUE, results = 'asis'}
for (i in seq_len(number_of_datasets)) {
  cf <- cf_nest$cf[[i]]
  dataset_id_no <- cf_nest$dataset_index[[i]]
  dataset <- datasets[[dataset_id_no]]

  data_id <- dataset$data_id
  header <- paste("Data ID =", data_id, sep = " ")
  cat("\n\n#### ", header, "\n\n")

  df <- dataset$data
  age_vars <- as.character(dataset$age_var)
  fixcov_names <- dataset$model$fixcov
  fixcov <- rep(0, length(fixcov_names))
  names(fixcov) <- fixcov_names

  pred <- helphlme::create_pred_df(
    df = df,
    age_vars = age_vars,
    fixcov = fixcov
  )

  age_var <- age_vars[[1]]
  outcome <- dataset$outcome
  ylim <- c(min(df[[outcome]]), max(df[[outcome]]))
  helphlme::display_classes(
    df = pred,
    x = cf$final_model,
    age = age_var,
    main = header,
    xlab = age_var,
    ylab = outcome,
    ylim = ylim
  )

  mo_eval <- helphlme::compare_models(cf$final_model)
  table <- kableExtra::kable(mo_eval$table)
  table <- kableExtra::kable_styling(table, "striped", full_width = FALSE)
  print(table)
  print(mo_eval$plot)
}
```

```{r select model in nest}
train_index <- sapply(datasets, `[[`, "data_mod") == "train_test"
complete_index <- !train_index

# params
complete_ng <- config$complete_ng
train_ng <- config$train_ng

complete_ng_bool <- length(complete_ng) == length(which(complete_index))
complete_ng_bool <- is.numeric(complete_ng) && complete_ng_bool
if (!complete_ng_bool) {
  complete_ng <- FALSE
}
train_ng_bool <- length(train_ng) == length(which(train_index))
train_ng_bool <- is.numeric(train_ng) && train_ng_bool
train_ng_bool <- train_ng_bool || identical(train_ng, "complete_ng")
if (!train_ng_bool) {
  train_ng <- FALSE
}

select_model <- function(cf, ng = FALSE) {
  data_id <- unique(cf$data)
  models <- cf$final_model
  mo_eval_table <- helphlme::compare_models(models)$table

  cf <- cbind(cf, mo_eval_table)
  # select model based on ng
  if (is.numeric(ng) && (length(ng) == 1L)) {
    cf <- cf[cf$ng == ng, ]
  }

  cf$smallest_greater_5 <- ifelse(cf[["Smallest Class (%)"]] >= 5, TRUE, FALSE)
  viable_models <- cf$smallest_greater_5 & (cf$conv == 1)
  cf <- cf[viable_models, ]
  cf <- cf[order(cf$BIC), ]

  selected_model <- cf[1, ]
}

selected_models_complete <- mapply(select_model,
  cf = cf_nest$cf[complete_index], ng = complete_ng, SIMPLIFY = FALSE
)

sapply(selected_models_complete, `[[`, "k")

if (train_ng == "complete_ng") {
  train_ng <- sapply(selected_models_complete, `[[`, "k")
}

selected_models_train <- mapply(select_model,
  cf = cf_nest$cf[train_index], ng = train_ng, SIMPLIFY = FALSE
)

sapply(selected_models_train, `[[`, "k")

selected_models <- c(selected_models_complete, selected_models_train)

selected_models <- do.call(rbind, selected_models)
```

```{r create final_models}
# here we are going to transfer information from dataset to final_models
final_model_rows <- lapply(seq_len(nrow(selected_models)), function(row_no) {
  row <- selected_models[row_no, ]
  dataset_index <- row$dataset_index
  dataset <- datasets[[dataset_index]]

  age_var <- dataset$age_var[[1]]
  data_oc <- paste(dataset$data_id, dataset$outcome, sep = "_")

  row$covariates <- list(dataset$covariates)
  row$fixcov <- list(dataset$model$fixcov)
  row$data_id <- dataset$data_id
  row$data_age_vars <- list(dataset$age_var)
  row$age_var <- age_var
  row$oc <- dataset$outcome
  row$data_oc <- data_oc
  row$model_name <- paste(data_oc, age_var, sep = "_")

  # we want to add labels as well from datasets
  row$oc_name <- dataset$labels$oc_name
  row$oc_units <- dataset$labels$oc_units
  row$age_var_name <- dataset$labels$age_var_name
  row$age_var_units <- dataset$labels$age_var_units
  row$data_name <- dataset$labels$data_name
  row$data_mod <- dataset$data_mod

  row
})

final_models <- do.call(rbind, final_model_rows)
```

```{r create final model csv}
column_select <- unique(c("model_name", names(final_models)))
drop_columns <- c("final_model", "covariates", "fixcov", "data_age_vars")
column_select_index <- !(column_select %in% drop_columns)
column_select <- column_select[column_select_index]

final_models_csv <- final_models[, column_select]
```

```{r save final models}
config_path <- input$config_path
config <- yaml::read_yaml(file = config_path)

output_path <- file.path("output", config$out_tag)
dir.create(output_path)
output_path <- normalizePath(output_path)

final_models_path <- file.path(output_path, "final_models.RDATA")
csv_path <- file.path(output_path, "final_models.csv")

write.csv(x = final_models_csv, file = csv_path)
save(final_models, file = final_models_path)

# create output file ----------------------------------------------------------
output_list <- list(
  data_time = format(Sys.time()),
  working_directory = getwd(),
  config_path = config_path,
  input_path = params$input_path,
  output_dir_path = output_path,
  datasets_path = input$datasets_path,
  models_path = input$models_path,
  cf_path = input$cf_path,
  final_models_path = final_models_path,
  csv_path = csv_path
)

output_list_path <- paste0(file.path("output", config$out_tag), ".yaml")
yaml::write_yaml(x = output_list, file = output_list_path)
```
