out_tag: test
tag_time: TRUE
female: 
het3: 
data_oc: 
  - "bw_main|bw"
  - "gluc_main|gluc"
  - "fat_main|fat"
  - "lean_main|lean"
  - "bwperxbl30_main|bw_per_x_bl30"
age_var: 
  - "age_wk"
  - "per_age_wk"
fixed: "~ $age_var + $age_var2 + female + het3" 
mixture: "~ $age_var + $age_var2" 
random: 
  - "~1"
subject: idno
idiag: FALSE
nwg: FALSE
ng_max: 3
plan: 
sample_n: 20
