---
title: "SLAM Metabolic Class Primary Figures"
author: "..."
data: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:
    df_print: paged
geometry:
  - top=1in
  - bottom=1in
  - left=0.5in
  - right=0.5in
---

```{r sup figs setup, warning=FALSE, message=FALSE, echo=FALSE}
library(helphlme)
library(tidyverse)
library(kableExtra)
library(survival)
library(survminer)
library(ggplotify)
library(sjPlot)
library(lme4)
library(cowplot)
library(RColorBrewer)
library(viridis)
library(consoler)
library(flextable)
library(future)
library(magick)
set.seed(365)

# setting global knitr options for r markdown output
knitr::opts_chunk$set(autodep = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = FALSE)
```


```{r sup figs read input yaml}
# this loads in all the tables
all_path <- "../07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/workspace.RDATA"
fb6_path <- "../07_display_figures/output/slam_c1-c10_age_fb6_bwfatgluc/workspace.RDATA"
fhet3_path <- "../07_display_figures/output/slam_c1-c10_age_fhet3_bwfatgluc/workspace.RDATA"
mb6_path <- "../07_display_figures/output/slam_c1-c10_age_mb6_bwfatgluc/workspace.RDATA"
mhet3_path <- "../07_display_figures/output/slam_c1-c10_age_mhet3_bwfatgluc/workspace.RDATA"
itp_path <- "../07_display_figures/output/itp_c10c11c13c16_age_controls_bw/workspace.RDATA"
held_out_path <- "../07_display_figures/output/slam_c1-10_x_slam_c16-18_age_bwfatgluc/workspace.RDATA"

config <- NULL
```

```{r sup figs load models, include = FALSE}
# Define a named list of input paths and environment names
render_tasks <- list(
  all_env = all_path,
  fb6_env = fb6_path,
  fhet3_env = fhet3_path,
  mb6_env = mb6_path,
  mhet3_env = mhet3_path,
  itp_env = itp_path,
  held_out_env = held_out_path
)

lapply(names(render_tasks), function(env_name) {
  env <- new.env()
  input_path <- render_tasks[[env_name]]
  load(input_path, envir = env)
  assign(env_name, env, envir = .GlobalEnv)
})
```

```{r sup figs fig no }
fig_no <- 1
tab_no <- 1
max_width <- 7
```

```{r save figure function}
save_figure <- function(image_obj, fig_num, label) {
  dir_path <- file.path("output", paste0("fig", fig_num))
  file_path <- file.path(dir_path, paste0(fig_num, label, ".png"))

  if (!dir.exists(dir_path)) {
    dir.create(dir_path, recursive = TRUE)
  }

  magick::image_write(image_obj, path = file_path, format = "png")
}
```

```{r annotate figure function}
annotate_figure_label <- function(image_obj, label) {
  magick::image_annotate(
    image_obj,
    text = toupper(label),
    size = 50,
    gravity = "northwest",
    location = "+20+20",
    color = "black"
  )
}
```

\newpage

\tableofcontents

\newpage

### Figure `r as.character(fig_no)`: Overview

```{r sup figs overview, out.width = "100%"}
fig1 <- list()
fig1$A <- image_read("images/Overview.png")
save_figure(fig1$A, "1", "A")

fig1$A

fig_no <- fig_no + 1
```

\newpage

### Figure `r as.character(fig_no)`: Defining Metabolic Classes

```{r define classes, out.width = "100%"}
fig2 <- list()
fig2$A <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/outcome/plot_1.png")
fig2$B <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/outcome/plot_4.png")
fig2$C <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/outcome/plot_7.png")
fig2$D <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/outcome/plot_10.png")
fig2$E <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/outcome/plot_2.png")
fig2$F <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/outcome/plot_5.png")
fig2$G <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/outcome/plot_8.png")
fig2$H <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/outcome/plot_11.png")
fig2$I <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/outcome/plot_3.png")
fig2$J <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/outcome/plot_6.png")
fig2$K <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/outcome/plot_9.png")
fig2$L <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/outcome/plot_12.png")
fig2$M <- image_read("images/Basic LCM.png")


for (label in names(fig2)) {
  save_figure(fig2[[label]], "2", label) # Save with correct label
  fig2[[label]] <- annotate_figure_label(fig2[[label]], label) # Annotate
}

# create table
hr_table <- do.call(rbind, all_env$save_figtabs$mortality_panel_hr)
hr_table <- cbind(Class = rownames(hr_table), hr_table)
hr_table <- flextable(hr_table) %>%
  theme_vanilla() %>%
  autofit() %>%
  set_table_properties(layout = "autofit") %>%
  fit_to_width(max_width = max_width, inc = .25, max_iter = 100)

invisible(save_as_image(hr_table, "output/mortality_panel_hr.png", zoom = 10))
fig2$N <- image_read("output/mortality_panel_hr.png")
fig2$N <- image_scale(fig2$N, "400%")
fig2$N <- image_border(fig2$N, color = "white", geometry = "100x100")
fig2$N <- annotate_figure_label(fig2$N, "N")


# Build rows of 4 images
row1 <- image_append(c(fig2$A, fig2$B, fig2$C, fig2$D), stack = FALSE)
row2 <- image_append(c(fig2$E, fig2$F, fig2$G, fig2$H), stack = FALSE)
row3 <- image_append(c(fig2$I, fig2$J, fig2$K, fig2$L), stack = FALSE)
row4 <- image_append(c(fig2$M, fig2$N))
# Stack the rows vertically
final_panel <- image_append(c(row1, row2, row3, row4), stack = TRUE)

# View or save
final_panel
# image_write(final_panel, "output/fig2/panel.png")

fig_no <- fig_no + 1
```


### Figure `r as.character(fig_no)`: Graded Mortality Response

```{r dose response, out.width = "100%"}
fig3 <- list()
fig3$A <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/dose_response/plot_1.png")
fig3$B <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/dose_response/plot_4.png")
fig3$C <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/dose_response/plot_7.png")


for (label in names(fig3)) {
  save_figure(fig3[[label]], "3", label) # Save with correct label
  fig3[[label]] <- annotate_figure_label(fig3[[label]], label) # Annotate
}

# create table

hr_table <- all_env$save_figtabs$dose_plot_panel_hr
hr_table <- lapply(hr_table, function(table) {
  table <- cbind(Quintile = seq_len(nrow(table)) + 1, table)
  table <- cbind(explicit = rownames(table), table)
  rownames(table) <- NULL
  table
})
hr_table <- cbind(explicit = rownames(hr_table), hr_table)
hr_table <- hr_table[c(1, 4, 7)]
hr_table <- do.call(rbind, hr_table)
hr_table <- flextable(hr_table) %>%
  theme_vanilla() %>%
  autofit() %>%
  set_table_properties(layout = "autofit") %>%
  fit_to_width(max_width = max_width, inc = .25, max_iter = 100)

invisible(save_as_image(hr_table, "output/km_validation_panel_hr.png", zoom = 10))
fig3$D <- image_read("output/km_validation_panel_hr.png")
fig3$D <- image_scale(fig3$D, "200%")
fig3$D <- image_border(fig3$D, color = "white", geometry = "100x100")
fig3$D <- annotate_figure_label(fig3$D, "D")

# Stack the rows vertically
col1 <- image_append(c(fig3$A, fig3$B, fig3$C), stack = TRUE)

final_panel <- image_append(c(col1, fig3$D), stack = FALSE)

# View or save
final_panel
# image_write(final_panel, "output/fig2/panel.png")
fig_no <- fig_no + 1
```

### Figure `r as.character(fig_no)`: Held Out Cohort Validation

```{r external validation, out.width = "100%"}
fig4 <- list()
fig4$A <- image_read("images/External Validation.png")
fig4$B <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-c10_age_all_bwfatgluc/forest/plot_5.png")
# fig4$C <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-10_x_slam_c16-18_age_bwfatgluc/km_combined_hr_validation/plot_[6.5, 32.5]_2.png")
fig4$C <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-10_x_slam_c16-18_age_bwfatgluc/km_combined_hr_validation/plot_[6.5, 58.5]_4.png")
fig4$D <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-10_x_slam_c16-18_age_bwfatgluc/km_combined_hr_validation/plot_[6.5, 84.5]_6.png")
fig4$E <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-10_x_slam_c16-18_age_bwfatgluc/km_combined_hr_validation/plot_[6.5, 110.5]_8.png")
fig4$F <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/slam_c1-10_x_slam_c16-18_age_bwfatgluc/km_combined_hr_validation/plot_[6.5, 136.5]_10.png")

fig4$A <- image_scale(fig4$A, "75%")
fig4$B <- image_scale(fig4$B, "125%")

for (label in names(fig4)) {
  save_figure(fig4[[label]], "4", label) # Save with correct label
  fig4[[label]] <- annotate_figure_label(fig4[[label]], label) # Annotate
}

# create table

hr_table <- held_out_env$save_figtabs$km_hr_combine_validation_panels_hr
hr_table <- lapply(hr_table, function(table) {
  table <- cbind(Tertile = seq_len(nrow(table)) + 1, table)
  table <- cbind(explicit = rownames(table), table)
  table$column <- rep(colnames(table)[3], nrow(table))
  colnames(table)[3] <- "HR"
  rownames(table) <- NULL
  table
})
hr_table <- cbind(explicit = rownames(hr_table), hr_table)
hr_table <- hr_table[c(2, 4, 6, 8, 10)]
hr_table <- do.call(rbind, hr_table)
hr_table <- flextable(hr_table) %>%
  theme_vanilla() %>%
  autofit() %>%
  set_table_properties(layout = "autofit") %>%
  fit_to_width(max_width = max_width, inc = .25, max_iter = 100)

invisible(save_as_image(hr_table, "output/km_validation_panel_hr.png", zoom = 10))
fig4$H <- image_read("output/km_validation_panel_hr.png")
fig4$H <- image_scale(fig4$H, "200%")
fig4$H <- image_border(fig4$H, color = "white", geometry = "100x100")
fig4$H <- annotate_figure_label(fig4$H, "H")


# Stack the rows vertically
col1 <- image_append(c(fig4$A, fig4$B), stack = TRUE)
col2 <- image_append(c(fig4$C, fig4$E), stack = TRUE)
col3 <- image_append(c(fig4$D, fig4$F), stack = TRUE)

final_panel <- image_append(c(col1, col2, col3), stack = FALSE)
final_panel <- image_append(c(final_panel, fig4$H), stack = TRUE)

# View or save
final_panel
# image_write(final_panel, "output/fig2/panel.png")
fig_no <- fig_no + 1
```

### Figure `r as.character(fig_no)`: ITP Validation

```{r ITP validation, out.width = "100%"}
fig5 <- list()
fig5$A <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/itp_c10c11c13c16_age_controls_bw/outcome/plot_1.png")
fig5$B <- image_read("/Users/williammueller/programs/metabolic_class/analysis/07_display_figures/output/itp_c10c11c13c16_age_controls_bw/outcome/plot_2.png")

for (label in names(fig5)) {
  save_figure(fig5[[label]], "5", label) # Save with correct label
  fig5[[label]] <- annotate_figure_label(fig5[[label]], label) # Annotate
}

# create table

hr_table <- itp_env$save_figtabs$mortality_panel_hr[[1]]
hr_table <- cbind(Class = rownames(hr_table), hr_table)
hr_table <- flextable(hr_table) %>%
  theme_vanilla() %>%
  autofit() %>%
  set_table_properties(layout = "autofit") %>%
  fit_to_width(max_width = max_width, inc = .25, max_iter = 100)

invisible(save_as_image(hr_table, "output/mortality_panel_hr.png", zoom = 10))
fig5$C <- image_read("output/mortality_panel_hr.png")
fig5$C <- image_scale(fig5$C, "400%")
fig5$C <- image_border(fig5$C, color = "white", geometry = "100x100")
fig5$C <- annotate_figure_label(fig5$C, "C")


# Stack the rows vertically
row1 <- image_append(c(fig5$A, fig5$B), stack = FALSE)
row2 <- fig5$C

final_panel <- image_append(c(row1, row2), stack = TRUE)

# View or save
final_panel
# image_write(final_panel, "output/fig2/panel.png")
fig_no <- fig_no + 1
```

