---
title: "SLAM Metabolic Class Figures Display"
author: "William Mueller"
data: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:
    df_print: paged
params:
  all_dir: "20220614_081638_all"
  mb6_dir: "20220614_163126_mb6"
  fb6_dir: "20220614_175701_fb6"
  mhet3_dir: "20220614_173921_mhet3"
  fhet3_dir: "20220614_160836_fhet3"
---

```{r setup, warning=FALSE, message=FALSE, echo=FALSE}
library(helphlme)
library(tidyverse)
library(kableExtra)
library(survival)
library(survminer)
library(ggplotify)
library(sjPlot)
library(lme4)
library(cowplot)
library(RColorBrewer)
# setting global knitr options for r markdown output
knitr::opts_chunk$set(autodep = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = FALSE)
```

## Analysis

### Load Models

```{r load models}
output_path <- file.path("..", "05_figures", "output")

load_models <- function(subgroup, envir = .GlobalEnv) {
  subgroup_param <- paste(subgroup, "dir", sep = "_")
  subgroup_path <- params[[subgroup_param]]
  path <- file.path(output_path,
                    subgroup_path,
                    "data",
                    "final_models.RDATA")
  env_name <- paste(subgroup, "env", sep = "_")
  assign(env_name, rlang::env(), envir = envir)
  load(path, eval(as.symbol(env_name)))
}

subgroups <- c("all", "mb6", "fb6", "mhet3", "fhet3")

for(subgroup in subgroups) {
  load_models(subgroup)
}

```

## Figures

### Figure 1: Dispaly How latent class models work

```{r figure 1}
p1 <- all_env$final_models[model_name == "bw_main|bw_age_wk", "spag_plot"]
p2 <- ggplot()
p3
```