center: TRUE
scale: FALSE
subsets: 
  - [sex: M, strain: HET3]
  - [sex: F, strain: HET3]
  - [sex: M, strain: B6]
  - [sex: F, strain: B6]
intervals:
  - [age_wk_ns: "(0, 57.50)"]
  - [age_wk_ns: "[57.50,86.25)"]
  - [age_wk_ns: "[86.25,103.50)"]
  - [age_wk_ns: "[103.50,Inf)"]
  - [age_wk_ns: "[57.50,103.50]"]
samples:
  - [idno: 1]
  - [idno: 2]
  - [idno: 3]
  - [idno: 4]
  - [idno: 5]
  - [idno: 6]
threshold:
  - [age_wk_ns: "(0, 20)"]
  - [age_wk_ns: "(0, 30)"]
  - [age_wk_ns: "(0, 40)"]
  - [age_wk_ns: "(0, 50)"]
  - [age_wk_ns: "(0, 60)"]
  - [age_wk_ns: "(0, 70)"]
  - [age_wk_ns: "(0, 80)"]
  - [age_wk_ns: "(0, 90)"]
  - [age_wk_ns: "(0, 100)"]
  - [age_wk_ns: "(0, 110)"]
  - [age_wk_ns: "(0, 120)"]
  - [age_wk_ns: "(0, 130)"]
  - [age_wk_ns: "(0, 140)"]
  - [age_wk_ns: "(0, 150)"]
  - [age_wk_ns: "(0, 160)"]
