center: TRUE
scale: FALSE
subsets: 
  - [sex: M, strain: HET3]
  - [sex: F, strain: HET3]
  - [sex: M, strain: B6]
  - [sex: F, strain: B6]
intervals:
  - [age_wk_ns: "(0, 57.50)"]
  - [age_wk_ns: "[57.50,86.25)"]
  - [age_wk_ns: "[86.25,103.50)"]
  - [age_wk_ns: "[103.50,Inf)"]
  - [age_wk_ns: "[57.50,103.50]"]
  - [age_wk_ns: "(0, 86.25]"]
  - [age_wk_ns: "(0, 103.50]"]
samples:
  - [idno: 1]
  - [idno: 2]
  - [idno: 3]
  - [idno: 4]
  - [idno: 5]
  - [idno: 6]

