center: TRUE
scale: FALSE
subsets: 
  - [sex: M, strain: HET3]
  - [sex: F, strain: HET3]
  - [sex: M, strain: B6]
  - [sex: F, strain: B6]
windows:
  - [age_wk_ns: "[0, 25]"]
  - [age_wk_ns: "[10, 35]"]
  - [age_wk_ns: "[20, 45]"]
  - [age_wk_ns: "[30, 55]"]
  - [age_wk_ns: "[40, 65]"]
  - [age_wk_ns: "[50, 75]"]
  - [age_wk_ns: "[60, 85]"]
  - [age_wk_ns: "[70, 95]"]
  - [age_wk_ns: "[80, 105]"]
  - [age_wk_ns: "[90, 115]"]
  - [age_wk_ns: "[100, 125]"]
  - [age_wk_ns: "[110, 135]"]
  - [age_wk_ns: "[120, 145]"]
  - [age_wk_ns: "[130, 155]"]
  - [age_wk_ns: "[140, 165]"]
  - [age_wk_ns: "[0, 50]"]
  - [age_wk_ns: "[10, 60]"]
  - [age_wk_ns: "[20, 70]"]
  - [age_wk_ns: "[30, 80]"]
  - [age_wk_ns: "[40, 90]"]
  - [age_wk_ns: "[50, 100]"]
  - [age_wk_ns: "[60, 110]"]
  - [age_wk_ns: "[70, 120]"]
  - [age_wk_ns: "[80, 130]"]
  - [age_wk_ns: "[90, 140]"]
  - [age_wk_ns: "[100, 150]"]
  - [age_wk_ns: "[110, 160]"]
samples:
  - [idno: 1]
  - [idno: 2]
  - [idno: 3]
  - [idno: 4]
  - [idno: 5]
  - [idno: 6]
  - [idno: 7]
  - [idno: 8]
  - [idno: 9]
  - [idno: 10]
threshold:
  - [age_wk_ns: "(0, 20)"]
  - [age_wk_ns: "(0, 30)"]
  - [age_wk_ns: "(0, 40)"]
  - [age_wk_ns: "(0, 50)"]
  - [age_wk_ns: "(0, 60)"]
  - [age_wk_ns: "(0, 70)"]
  - [age_wk_ns: "(0, 80)"]
  - [age_wk_ns: "(0, 90)"]
  - [age_wk_ns: "(0, 100)"]
  - [age_wk_ns: "(0, 110)"]
  - [age_wk_ns: "(0, 120)"]
  - [age_wk_ns: "(0, 130)"]
  - [age_wk_ns: "(0, 140)"]
  - [age_wk_ns: "(0, 150)"]
  - [age_wk_ns: "(0, 160)"]
  - [age_wk_ns: "(50, 70)"]
  - [age_wk_ns: "(50, 80)"]
  - [age_wk_ns: "(50, 90)"]
  - [age_wk_ns: "(50, 100)"]
  - [age_wk_ns: "(50, 110)"]
  - [age_wk_ns: "(50, 120)"]
  - [age_wk_ns: "(50, 130)"]
  - [age_wk_ns: "(50, 140)"]
  - [age_wk_ns: "(50, 150)"]
  - [age_wk_ns: "(50, 160)"]
  - [age_wk_ns: "(70, 90)"]
  - [age_wk_ns: "(70, 100)"]
  - [age_wk_ns: "(70, 110)"]
  - [age_wk_ns: "(70, 120)"]
  - [age_wk_ns: "(70, 130)"]
  - [age_wk_ns: "(70, 140)"]
  - [age_wk_ns: "(70, 150)"]
  - [age_wk_ns: "(70, 160)"]
  - [age_wk_ns: "(100, 120)"]
  - [age_wk_ns: "(100, 130)"]
  - [age_wk_ns: "(100, 140)"]
  - [age_wk_ns: "(100, 150)"]
  - [age_wk_ns: "(100, 160)"]
